package  movies.app.movies.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MOVIES".
 */
public class Movies {

    /** Not-null value. */
    private String uuid;
    private String title;
    private Integer year;
    private String rated;
    private java.util.Date released;
    private Long runTime;
    private String genre;
    private String director;
    private String actors;
    private String plot;
    private String language;
    private String awards;
    private String poster;
    private Long metaScore;
    private Long imdbRating;
    private String type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Movies() {
    }

    public Movies(String uuid) {
        this.uuid = uuid;
    }

    public Movies(String uuid, String title, Integer year, String rated, java.util.Date released, Long runTime, String genre, String director, String actors, String plot, String language, String awards, String poster, Long metaScore, Long imdbRating, String type) {
        this.uuid = uuid;
        this.title = title;
        this.year = year;
        this.rated = rated;
        this.released = released;
        this.runTime = runTime;
        this.genre = genre;
        this.director = director;
        this.actors = actors;
        this.plot = plot;
        this.language = language;
        this.awards = awards;
        this.poster = poster;
        this.metaScore = metaScore;
        this.imdbRating = imdbRating;
        this.type = type;
    }

    /** Not-null value. */
    public String getUuid() {
        return uuid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public String getRated() {
        return rated;
    }

    public void setRated(String rated) {
        this.rated = rated;
    }

    public java.util.Date getReleased() {
        return released;
    }

    public void setReleased(java.util.Date released) {
        this.released = released;
    }

    public Long getRunTime() {
        return runTime;
    }

    public void setRunTime(Long runTime) {
        this.runTime = runTime;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public String getDirector() {
        return director;
    }

    public void setDirector(String director) {
        this.director = director;
    }

    public String getActors() {
        return actors;
    }

    public void setActors(String actors) {
        this.actors = actors;
    }

    public String getPlot() {
        return plot;
    }

    public void setPlot(String plot) {
        this.plot = plot;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getAwards() {
        return awards;
    }

    public void setAwards(String awards) {
        this.awards = awards;
    }

    public String getPoster() {
        return poster;
    }

    public void setPoster(String poster) {
        this.poster = poster;
    }

    public Long getMetaScore() {
        return metaScore;
    }

    public void setMetaScore(Long metaScore) {
        this.metaScore = metaScore;
    }

    public Long getImdbRating() {
        return imdbRating;
    }

    public void setImdbRating(Long imdbRating) {
        this.imdbRating = imdbRating;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
