package movies.app.movies.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import movies.app.movies.dao.Movies;

import movies.app.movies.dao.MoviesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig moviesDaoConfig;

    private final MoviesDao moviesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        moviesDaoConfig = daoConfigMap.get(MoviesDao.class).clone();
        moviesDaoConfig.initIdentityScope(type);

        moviesDao = new MoviesDao(moviesDaoConfig, this);

        registerDao(Movies.class, moviesDao);
    }
    
    public void clear() {
        moviesDaoConfig.getIdentityScope().clear();
    }

    public MoviesDao getMoviesDao() {
        return moviesDao;
    }

}
