package movies.app.movies.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "MOVIES".
 */
public class Movies implements Parcelable {

    /** Not-null value. */
    private String imdbID;
    private String Title;
    private String Year;
    private String Rated;
    private String Released;
    private String Runtime;
    private String Genre;
    private String Director;
    private String Actors;
    private String Plot;
    private String Language;
    private String Awards;
    private String Poster;
    private String MetaScore;
    private String imdbRating;
    private String Type;
    private String Writer;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Movies() {
    }

    public Movies(String imdbID) {
        this.imdbID = imdbID;
    }

    public Movies(String imdbID, String Title, String Year, String Rated, String Released, String Runtime, String Genre, String Director, String Actors, String Plot, String Language, String Awards, String Poster, String MetaScore, String imdbRating, String Type, String Writer) {
        this.imdbID = imdbID;
        this.Title = Title;
        this.Year = Year;
        this.Rated = Rated;
        this.Released = Released;
        this.Runtime = Runtime;
        this.Genre = Genre;
        this.Director = Director;
        this.Actors = Actors;
        this.Plot = Plot;
        this.Language = Language;
        this.Awards = Awards;
        this.Poster = Poster;
        this.MetaScore = MetaScore;
        this.imdbRating = imdbRating;
        this.Type = Type;
        this.Writer = Writer;
    }

    protected Movies(Parcel in) {
        imdbID = in.readString();
        Title = in.readString();
        Year = in.readString();
        Rated = in.readString();
        Released = in.readString();
        Runtime = in.readString();
        Genre = in.readString();
        Director = in.readString();
        Actors = in.readString();
        Plot = in.readString();
        Language = in.readString();
        Awards = in.readString();
        Poster = in.readString();
        MetaScore = in.readString();
        imdbRating = in.readString();
        Type = in.readString();
        Writer = in.readString();
    }

    public static final Creator<Movies> CREATOR = new Creator<Movies>() {
        @Override
        public Movies createFromParcel(Parcel in) {
            return new Movies(in);
        }

        @Override
        public Movies[] newArray(int size) {
            return new Movies[size];
        }
    };

    /** Not-null value. */
    public String getImdbID() {
        return imdbID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImdbID(String imdbID) {
        this.imdbID = imdbID;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getYear() {
        return Year;
    }

    public void setYear(String Year) {
        this.Year = Year;
    }

    public String getRated() {
        return Rated;
    }

    public void setRated(String Rated) {
        this.Rated = Rated;
    }

    public String getReleased() {
        return Released;
    }

    public void setReleased(String Released) {
        this.Released = Released;
    }

    public String getRuntime() {
        return Runtime;
    }

    public void setRuntime(String Runtime) {
        this.Runtime = Runtime;
    }

    public String getGenre() {
        return Genre;
    }

    public void setGenre(String Genre) {
        this.Genre = Genre;
    }

    public String getDirector() {
        return Director;
    }

    public void setDirector(String Director) {
        this.Director = Director;
    }

    public String getActors() {
        return Actors;
    }

    public void setActors(String Actors) {
        this.Actors = Actors;
    }

    public String getPlot() {
        return Plot;
    }

    public void setPlot(String Plot) {
        this.Plot = Plot;
    }

    public String getLanguage() {
        return Language;
    }

    public void setLanguage(String Language) {
        this.Language = Language;
    }

    public String getAwards() {
        return Awards;
    }

    public void setAwards(String Awards) {
        this.Awards = Awards;
    }

    public String getPoster() {
        return Poster;
    }

    public void setPoster(String Poster) {
        this.Poster = Poster;
    }

    public String getMetaScore() {
        return MetaScore;
    }

    public void setMetaScore(String MetaScore) {
        this.MetaScore = MetaScore;
    }

    public String getImdbRating() {
        return imdbRating;
    }

    public void setImdbRating(String imdbRating) {
        this.imdbRating = imdbRating;
    }

    public String getType() {
        return Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

    public String getWriter() {
        return Writer;
    }

    public void setWriter(String Writer) {
        this.Writer = Writer;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeString(imdbID);
        parcel.writeString(Title);
        parcel.writeString(Year);
        parcel.writeString(Rated);
        parcel.writeString(Released);
        parcel.writeString(Runtime);
        parcel.writeString(Genre);
        parcel.writeString(Director);
        parcel.writeString(Actors);
        parcel.writeString(Plot);
        parcel.writeString(Language);
        parcel.writeString(Awards);
        parcel.writeString(Poster);
        parcel.writeString(MetaScore);
        parcel.writeString(imdbRating);
        parcel.writeString(Type);
        parcel.writeString(Writer);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
